[M146] Cherry pick notify mode changes.
[dawn][common] Adds different Notify modes for MutexCondVarProtected.

- Adds an optional template argument for MutexCondVarProtected users
  to explicitly specify notify mode. Sometimes, we may modify the
  inner object but may want to not notify, or notify only one thread.
- Additionally, this change has some cleanups to remove the unused
  MutexProtectedSupport class that I initially added a while back
  thinking it would be useful, but we have since found other ways
  to address the initial use case in MapAsync. It also greatly
  simplifies the code by removing the inheritance that made it quite
  hard to update.

Change-Id: I3c22ecd4ab3fab4149a999ed78474b175c52b1c3
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/290375
Reviewed-by: Corentin Wallez <cwallez@chromium.org>
Commit-Queue: Loko Kung <lokokung@google.com>

[dawn] Minor fix for dawn node build failure

GCC fails but clang succeeds.
https://godbolt.org/z/79oczKWff

Original CL: https://dawn-review.git.corp.google.com/c/dawn/+/290375

The original error:
error: too few template-parameter-lists [-Wtemplate-body]

Change-Id: I8cdaa8a4d19ee3be1defd41c06a87df66d29be51
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/292896
Commit-Queue: Peter McNeeley <petermcneeley@google.com>
Reviewed-by: dan sinclair <dsinclair@chromium.org>
Reviewed-by: Loko Kung <lokokung@google.com>
Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/298395
Reviewed-by: Kai Ninomiya <kainino@chromium.org>
Commit-Queue: Loko Kung <lokokung@google.com>